### ISSUE TITLE
[Bug] [dlink-catalog-mysql-1.16] META-INF/services folder not created

### ISSUE THREAD

**Issue by lugela** [DataLinkDC/dinky#1421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

META-INF/services folder not created

error:
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'dlink_mysql' that implements 'org.apache.flink.table.factories.CatalogFactory' in the classpath.

Available factory identifiers are:

generic_in_memory
        at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:545)
        at org.apache.flink.table.factories.FactoryUtil.getCatalogFactory(FactoryUtil.java:723)
        at org.apache.flink.table.factories.FactoryUtil.createCatalog(FactoryUtil.java:420)
        ... 79 more

![image](https://user-images.githubusercontent.com/18652779/207033581-9565899a-2733-4079-9282-56f98b2904f1.png)

### What you expected to happen

dlink-0.7/dev etc
META-INF/services folder not created

error:
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'dlink_mysql' that implements 'org.apache.flink.table.factories.CatalogFactory' in the classpath.

Available factory identifiers are:

generic_in_memory
        at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:545)
        at org.apache.flink.table.factories.FactoryUtil.getCatalogFactory(FactoryUtil.java:723)
        at org.apache.flink.table.factories.FactoryUtil.createCatalog(FactoryUtil.java:420)
        ... 79 more

![image](https://user-images.githubusercontent.com/18652779/207033581-9565899a-2733-4079-9282-56f98b2904f1.png)

### How to reproduce

no 

### Anything else

no

### Version

0.7.0

### Are you willing to submit PR?

- [ ] No I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aiwenmo** [comment]
Hi. You're right. Would you like to submit a PR? thx.

**Comment by lugela** [comment]
Sorry, I accidentally pressed it. This is add  just a file, so I won't submit it.

**Comment by aiwenmo** [comment]
Thanks.  I will to submit a PR.
