### ISSUE TITLE
[Bug] [meta] Doris datasource support [ MAP ] type

### ISSUE THREAD

**Issue by gaoyan1998** [DataLinkDC/dinky#3589]
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

type covert is wrong

![Image](https://github.com/DataLinkDC/dinky/assets/34333571/5ffc2898-ff59-45b8-aed6-fc38c36114e9)

### What you expected to happen

type covert is wrong

### How to reproduce

type covert is wrong

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
