### ISSUE TITLE
[Feature][admin] Task submit support approval

### ISSUE THREAD

**Issue by MactavishCui** [DataLinkDC/dinky#4061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, Dinky has implemented the features including auth management, task version control to support team development cooperation. In my opinion task review is also an important feature for team development .The code and configuration review before deployment can help teams make a better data ware house quality. As a result, l proposed this task approval feature.

### Use case

In order to implement task approval, l think dinky should have following abilities:
## Approval configuration center
It has following options:
 - Enable task approval: When this option is disabled, there's nothing different of task submit process between previous and new dinky version, otherwise, a task cannot be submitted unless it has been approved.
 - Enforce cross review: Reviewer and submitter cannot be the same user in one approval when this option is enabled.
 - Reviewer roles: Roles who can approve or reject an approval.
The following pics list my attempts, mentioned options can be changed in configuration center:
![0adfcd68eb3912fab90dab6fccb9fec](https://github.com/user-attachments/assets/0fc4db3f-6b99-401c-b5c4-393b1352e0a2)
## Task submit aspect
The pic below shows the process of task submit with approval. 
 - Front end: When a task need to be approved first(Enable task approval and no approved process exists for current version), user need to publish the task first and then submit an approval. Only when the task has been approved, users can request the TaskController.submit interface by dinky-web. 
 - Back end: An approval aspect is designed to check if approval is needed and whether it has been approved before submit. If the task is not allowed to be submitted, an exception will be thrown
![image](https://github.com/user-attachments/assets/5b601b0a-91ae-4774-9440-6e73d1424ec6)
![c70548cea83c2c88cb10343bfb72dfb](https://github.com/user-attachments/assets/4e7570c4-a42e-49ee-8caa-d3c409053258)

## Approval Center
In this page ,users can get the approvals they submitted or required for review. Like what has been implemented below, users can do some operations including withdraw, reject and approve. The different between previous and current version can also be reviewed Approval search is also supported.

pic task approval list
![1bb8206efdcd356b12ee517ae3bfb05](https://github.com/user-attachments/assets/00ba1ebd-6b6c-4e9a-af85-e15a2829af94)

pic task info
![fbc900508a31a26fc42742c55c9a25f](https://github.com/user-attachments/assets/2f52a0a2-3560-49f6-bf30-2ff92f932d24)

pic reject or approve
![8fffe22620bf6f1d59af710cc6231ae](https://github.com/user-attachments/assets/546c8c82-935a-41cd-8ed3-115b2519be0a)

pic approval status and handle event
![image](https://github.com/user-attachments/assets/0875cc9f-b1fe-43e7-81fe-5baa8229981b)

Of course, when enable task approval configuration is disabled, this page is also not available:
![6fce989b371002b19cdb505ad4025d9](https://github.com/user-attachments/assets/7263fdb5-05f8-4222-9bd1-4d947031c306)

All mentioned above is my new attempt about task approval. What is your opinion about this feature and my scheme?
Looking forward to your reply and discussion!

### Related issues

No

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zzm0809** [comment]
If you need to implement such a function, whether you need to add the function of on-site notification to remind the corresponding approver for approval, and at the same time, you can generate the corresponding approval form link for quick approval

**Comment by aiwenmo** [comment]
Thank you very much for your suggestion on the approval function.

I think the approval management page should be in the authentication center (or other center) instead of adding a new approval center.

**Comment by gaoyan1998** [comment]
> If you need to implement such a function, whether you need to add the function of on-site notification to remind the corresponding approver for approval, and at the same time, you can generate the corresponding approval form link for quick approval

I think this can be considered later. It is an optimization and does not affect the existing logic. You can continue to add such functions after the current task is completed.

**Comment by MactavishCui** [comment]
> If you need to implement such a function, whether you need to add the function of on-site notification to remind the corresponding approver for approval, and at the same time, you can generate the corresponding approval form link for quick approval



> > If you need to implement such a function, whether you need to add the function of on-site notification to remind the corresponding approver for approval, and at the same time, you can generate the corresponding approval form link for quick approval
> 
> I think this can be considered later. It is an optimization and does not affect the existing logic. You can continue to add such functions after the current task is completed.

Thx for your reply. Firstly, thanks for your suggestion, I agree with @Zzm0809 it will be helpful to remind users and generate an approval link. And I also agree with what @gaoyan1998 said, I think after finishing current task maybe an alert instance can be build or other methods can be used to notify users, which can improve this function better. And I'm willing to continue working on it.

**Comment by MactavishCui** [comment]
> Thank you very much for your suggestion on the approval function.
> 
> I think the approval management page should be in the authentication center (or other center) instead of adding a new approval center.

@aiwenmo Thanks for your suggestion! The reason I add a new approval center page is that I think in the future, more process can be controlled by approval like datasource register, document management and so on. I agree with your idea that in current version, it will be better to put approval page into auth center. I'll update codes today based on the new page layout.

**Comment by MactavishCui** [comment]
Besides, may I divide this function implement into several small PRs and submit them step by step?  I think it can be divided into these steps:
1. Approval configuration.
2. Approval handle back end part implement and test cases. 
3. Approval management page front end part implement.
4. Task submit aspect

Looking forward to your reply

**Comment by aiwenmo** [comment]
@MactavishCui OK. 

Besides, in the future, when more processes are controlled by approval, **an approval center should not be added either**, because approval is **an auxiliary function** and it should be classified into one center. 

Looking forward to your PR

**Comment by MactavishCui** [comment]
> @MactavishCui OK.
> 
> Besides, in the future, when more processes are controlled by approval, **an approval center should not be added either**, because approval is **an auxiliary function** and it should be classified into one center.
> 
> Looking forward to your PR

@aiwenmo Thanks a lot! Your reply helps me understand the page layout design better, and that can surely helps me a lot in further contribution to dinky! 
I'll submit the first PR this week!

**Comment by Zzm0809** [comment]
Thank you for your contribution
