### ISSUE TITLE
[Feature][Style] Added system java code style

### ISSUE THREAD

**Issue by zhuangchong** [DataLinkDC/dinky#880]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Add code style

- [x]  #868 
- [x] Added dlink-admin module code style #889 
- [x] Added dlink-alert module code style #891
- [x] Added dlink-app module code style #899
- [x] Added dlink-catalog module code style #895 
- [x] Added dlink-client module code style #898 
- [x] Added dlink-common module code style #892 
- [x] Added dlink-connectors module code style #913 
- [x] Added dlink-core module code style #917 
- [x] Added dlink-daemon module code style #918
- [x] Added dlink-executor module code style #919 
- [x] Added dlink-function module code style #920 
- [x] Added dlink-gateway module code style #920 
- [x] Added dlink-metadata module code style #921 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhuangchong** [comment]
done.
